### ISSUE TITLE
flowdec installation downloads tensorflow when tensorflow-gpu already installed

### ISSUE THREAD

**Issue by elktoe** [hammerlab/flowdec#10]
Hi!
When running the e.elegans example flowdec was running on CPU, not GPU. Also noticed that when flowdec was installed it installed tensorflow and not tensorflow-gpu. 

If tensorflow was uninstalled would flowdec use tensorflow-gpu and sort itself out?
Cheers

**Comment by russellb** [comment]
Try installing flowdec with the `TF_GPU` environment variable set to `true`.

It might be better to just document the tensorflow requirement and not try to automatically install tensorflow or tensorflow-gpu automatically.

**Comment by eric-czech** [comment]
For posterity here, the TF dependency was split out as an extra to be installed on request based on user preferences (see instructions in [README](https://github.com/hammerlab/flowdec#installation)) per fix from @russellb in https://github.com/hammerlab/flowdec/pull/11
