### ISSUE TITLE
TypeError: unexpected keyword argument: img_num

### ISSUE THREAD

**Issue by naureeng** [hammerlab/flowdec#22]
I am using a virtual conda environment with TensorFlow 1.13.1 and I cannot import the C. elegans dataset. This is a picture of the error I get
![issue](https://user-images.githubusercontent.com/32179063/57154763-8d6f8800-6dd1-11e9-9a4b-a511708aaf61.PNG)

**Comment by eric-czech** [comment]
As a workaround, you could switch to scikit-image 0.14.0 (i.e. ```pip install scikit-image==0.14.0```).

I'll leave this open though in case someone (probably me) gets a chance to either either pin it as a requirement or figure out a way to make it work with newer scikit-image versions.

**Comment by naureeng** [comment]
Thanks for the reply! There is a bug between numpy 1.16 and scikit-image 0.14.0/0.14.1
https://github.com/scikit-image/scikit-image/issues/3586

I installed scikit-image 0.14.2 to get it working
