### ISSUE TITLE
ResourceExhaustedError 

### ISSUE THREAD

**Issue by naureeng** [hammerlab/flowdec#25]
Dear Eric,

I tried to deconvolve two identical stacks. One works and the other results in a ResourceExhuastedError. I've attached the ImageJ headers:

(1) 2048x2048pixels  (does not work)
(2) 204.4x204.4microns (works)

![ques](https://user-images.githubusercontent.com/32179063/58560429-06b99980-821d-11e9-8d01-f6a3299af556.JPG)

**Comment by eric-czech** [comment]
Hi @naureeng, it looks like the one is 2044x2044 pixels and the other is 2048x2048 right?  They should certainly both work if the larger one works so my very first question would be whether or not you're doing this in two separate jupyter notebooks (or IPython kernels).  If you are, then whichever one you ran first will allocate all (or most) of the GPU memory and the other will likely fail.  You'd have to run them in the same process or set the TensorFlow options that control how much memory is used to make it less than 50% for each process.

If it's not that, then if you send some code or more information on what you're doing I could probably help.

**Comment by naureeng** [comment]
I'm not sure what it was but the micron units works a lot faster for some reason... I will close the issue for now.
