### ISSUE TITLE
choosing parameters for Lightsheet microscopy data

### ISSUE THREAD

**Issue by jesusdpa1** [hammerlab/flowdec#30]
Hi Eric, 

I am planning on using flowdec to apply deconvolution for Lightsheet microscopy. I think you have the parameter extraction already integrated into cytokit with the experiment json file, but is there a way of doing the same thing directly with flowdec to apply for this type of images?

**Comment by eric-czech** [comment]
Certainly, there are several discussions in the issues on using this lib for lightsheet images specifically too (e.g. https://github.com/hammerlab/flowdec/issues/12). The examples in the repo show lots of different ways to do it.  This [notebook](https://github.com/hammerlab/flowdec/blob/master/python/validation/psfgeneration/validation.ipynb) shows arguments for the psf generator and [01_Lattice_Light_Sheet_Deconvolution.ipynb](https://github.com/VolkerH/Lattice_Lightsheet_Deskew_Deconv/blob/f862ccb0a2ea967259a7bb9494bdbcbc497c4256/examples/01_Lattice_Light_Sheet_Deconvolution.ipynb) is a great tutorial.  There is also a tutorial on deconvolving images too large for gpu memory using dask [here](https://github.com/hammerlab/flowdec/blob/f565324b09a1fbd0c8b676fe7a160f07a6d35d79/python/examples/notebooks/Tile-by-tile%20deconvolution%20using%20dask.ipynb).

**Comment by jesusdpa1** [comment]
Thanks!!
