### ISSUE TITLE
PSF min max and type.

### ISSUE THREAD

**Issue by joaomamede** [hammerlab/flowdec#36]
Should the PSF be Float32 with min being 0 and max being 1?

Can I use an acquired PSF straight from a 16bit image? Or should I contrast from 0 to 1?

Thanks.

**Comment by eric-czech** [comment]
All you need for a PSF is non-negative values.  It would be converted to float32 (by default) and rescaled to sum to 1, but you don't need to do either of those things beforehand.

**Comment by joaomamede** [comment]
That's awesome! I'm having great results with flowdec. It already deconvolved 22TB of data :) 
Thanks again
