### ISSUE TITLE
Deconvolution use pixel based psf 

### ISSUE THREAD

**Issue by romainGuiet** [hammerlab/flowdec#41]
Dear flowdec team,

thank you for releasing this tool!

I have a rather simple question but I couldn't reach a definitive answer while going through your excellent documentation.

Does the deconvolution process use pixel based psf (regardless of the psf voxel dimension) ? As in, should the pixel sizes of the PSF be identical to those of the image to deconvolve?
or 
Does it resize the given psf so it will match the voxel dimensions of the image to deconvolve ?

From reading the code and documentation, my guess is that it's pixel-based but I'll be happy to have a confirmation.

Thank you again,

Best,

Romain

**Comment by eric-czech** [comment]
Hi @romainGuiet,

> thank you for releasing this tool!

👍 

> should the pixel sizes of the PSF be identical to those of the image to deconvolve?

That's right, the voxel sizes of both the image and the PSF should be the same.  There is nothing in the library that attempts to resample the PSF up or down to match the image.

**Comment by romainGuiet** [comment]
Thank you for your answer !
